---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - functions.oci.oracle.com
  resources:
  - functionjobs
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - functions.oci.oracle.com
  resources:
  - functionjobs/finalizers
  - functions/finalizers
  - functionworkflowruns/finalizers
  verbs:
  - update
- apiGroups:
  - functions.oci.oracle.com
  resources:
  - functionjobs/status
  - functions/status
  - functionworkflowruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - functions.oci.oracle.com
  resources:
  - functions
  - functionworkflowruns
  - functionworkflows
  verbs:
  - get
  - list
  - watch
