apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: INVOKER_MODE
          value: oci
        - name: OCI_AUTH_MODE
          valueFrom:
            configMapKeyRef:
              name: oci-functions-operator-oci-mode
              key: OCI_AUTH_MODE
        - name: OCI_RESOURCE_PRINCIPAL_VERSION
          valueFrom:
            configMapKeyRef:
              name: oci-functions-operator-oci-mode
              key: OCI_RESOURCE_PRINCIPAL_VERSION
        - name: OCI_RESOURCE_PRINCIPAL_REGION
          valueFrom:
            configMapKeyRef:
              name: oci-functions-operator-oci-mode
              key: OCI_RESOURCE_PRINCIPAL_REGION
